version: 2

registries:
  hcp-terraform:
    type: terraform-registry
    url: https://app.terraform.io
    token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

updates:
- package-ecosystem: terraform
  directory: /
  registries: hcp-terraform
  schedule:
    interval: weekly

- package-ecosystem: terraform
  directory: /
  schedule:
    interval: weekly

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
